const fs = require('fs');
let c = fs.readFileSync('src/pages/MyMinee.tsx', 'utf-8');

c = c.replace(/import \{ validateAdminToken \} from '\.\.\/lib\/token';/, "import { useWorkspace } from '../context/WorkspaceContext';");

// find MyMinee component start
c = c.replace(/export default function MyMinee\(\) \{/, `export default function MyMinee() {\n  const { workspaceId } = useWorkspace();\n  const isFathur = workspaceId === 'fathur';\n  const [accessStatus, setAccessStatus] = useState<'none' | 'pending' | 'approved'>(isFathur ? 'approved' : 'none');\n\n  useEffect(() => {\n    if (isFathur) return;\n    supabase.from('app_config').select('value').eq('key', 'myminee_access_mazet').single().then(({data}) => {\n      if (data?.value?.status) setAccessStatus(data.value.status);\n    });\n  }, [isFathur]);\n\n  const handleRequestAccess = async () => {\n    setUnlocking(true);\n    try {\n      await supabase.from('app_config').upsert({ key: 'myminee_access_mazet', value: { status: 'pending', requestedAt: Date.now() }, updated_at: new Date().toISOString() });\n      \n      // get admin user ID\n      const { data: adminData } = await supabase.from('profiles').select('uid').eq('workspace_id', 'fathur').single();\n      if (adminData?.uid) {\n        await supabase.from('notifications').insert({\n          user_id: adminData.uid,\n          title: 'Permintaan Akses My Minee',\n          message: 'Mazet meminta akses untuk membuka galeri My Minee.',\n          type: 'security',\n          read: false\n        });\n      }\n      setAccessStatus('pending');\n    } catch (e) {\n      console.error(e);\n      setUnlockError('Gagal mengirim permintaan.');\n    } finally {\n      setUnlocking(false);\n    }\n  };\n\n  const handleApproveAccess = async () => {\n    setUnlocking(true);\n    try {\n      await supabase.from('app_config').upsert({ key: 'myminee_access_mazet', value: { status: 'approved', approvedAt: Date.now() }, updated_at: new Date().toISOString() });\n      \n      const { data: mazetData } = await supabase.from('profiles').select('uid').eq('workspace_id', 'mazet').single();\n      if (mazetData?.uid) {\n        await supabase.from('notifications').insert({\n          user_id: mazetData.uid,\n          title: 'Akses My Minee Disetujui',\n          message: 'Fathur telah menyetujui akses kamu ke My Minee!',\n          type: 'achievement',\n          read: false\n        });\n      }\n      setAccessStatus('approved');\n    } catch (e) {}\n    setUnlocking(false);\n  };\n`);

fs.writeFileSync('src/pages/MyMinee.tsx', c);
